variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build

# test:
#   image: node:10.15-alpine
#   stage: test
#   before_script:
#     - "npm install"
#   script: "CI=true npm run test"

build:
  image: docker:stable
  services:
  - docker:dind
  before_script:
    - docker info
  stage: build
  script:
    - docker build -t dohaicuong/react-app .
    - docker login -u dohaicuong -p haicuong
    - docker push dohaicuong/react-app:latest