image: node:10.15-alpine

stages:
  - install_dependences
  - test
  - build

job 1:
  stage: install_dependences
  script: npm install

job 2:
  stage: test
  script: CI=true npm test

job 3:
  stage: build
  script: npm run build