image: node:10.15-alpine

stages:
  - test
  - build
  - deploy

job:
  stage: test
  before_script:
    - "npm install"
  script: "CI=true npm run test"

job 2:
  stage: build
  before_script:
   - docker info

  build_image:
   script:
     - docker build -t my-react-app .
     # - docker run my-docker-image /script/to/run/tests